######################################################################
# Automatically generated by qmake (2.01a) ??? ??? 21 03:30:54 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += PaSpyRouter2016QtCpp.cpp
RESOURCES += PaSpyRouter2016QtCpp.qrc
